### ISSUE TITLE
Add a module to emit standard events

### ISSUE THREAD

**Issue by dmkozh** [stellar/rs-soroban-sdk#866] opened 2023-02-14 18:41 UTC
We need to provide a library (probably a module in SDK) to provide simple access to the standard events (such as token events). Besides the token events, we also need a `trade` event to cover various trading contracts.

**Comment by sisuresh** [comment] 2023-02-14 19:01
This is a duplicate of https://github.com/stellar/rs-soroban-sdk/issues/812, except this also mentions the trade event. Closing this in favor of the other one and added a comment for the trade event. Please add details to the other issue if anything is missing.

**Closed by sisuresh** 2023-02-14 19:01 UTC
