### ISSUE TITLE
Provide a combined token interface in the SDK

### ISSUE THREAD

**Issue by sisuresh** [stellar/rs-soroban-sdk#1030] opened 2023-07-06 22:17 UTC
We currently have two interfaces that we can create clients from `Interface` and `StellarAssetAdminInterface`, but we don''t provide a single client with the combined interface.  I tried `pub trait CompleteInterface: Interface + StellarAssetAdminInterface {}`, but this doesn't work because the `contractclient` macro doesn't find the inherited methods. I also tried just copying the methods into a combined interface, but there were naming conflicts (Ex. __SPEC_XDR_FN_APPROVE was defined multiple times).

**Comment by leighmcculloch** [comment] 2023-08-19 00:30
> Provide a combined token interface in the SDK

What's the use case for having a combined interface?

**Comment by sisuresh** [comment] 2023-08-19 01:15
> > Provide a combined token interface in the SDK
> 
> What's the use case for having a combined interface?

It's mainly to avoid situations like https://github.com/stellar/soroban-examples/blob/bddac245ed6f3ae660f011a16133167d38ecfbd2/atomic_swap/src/test.rs#L13-L18 in tests where you need to create both interfaces and use them in tandem. In addition to that, any contract that wants to call `transfer` and `mint` will either need both interfaces, or use a token wasm client like we do in the liquidity pool example.

**Comment by leighmcculloch** [comment] 2023-08-25 22:56
> where you need to create both interfaces and use them in tandem

This is inconvenient, but by design and a tradeoff that @graydon and I came to when addressing:
- https://github.com/stellar/rs-soroban-sdk/issues/268

> I tried `pub trait CompleteInterface: Interface + StellarAssetAdminInterface {}`
> I also tried just copying the methods into a combined interface

I think we could make the second approach work with the use of some macros and namespacing, but I'm not convinced we should.

Today the SDK exposes:
- `token::Interface` and `token::Client` – The only methods tokens need to be interoperable.
- `token::StellarAssetAdminInterface` and `token::AdminClient`\* –  Interface and client for convenience calling a SAC.

If we add a third interface for tokens, we create decisions for developers to navigate, and it's unclear to me if that cost outweighs the value added. Developers will see:
- `token::Interface` and `token::Client` – The only methods tokens need to be interoperable.
- `token::StellarAssetAdminInterface` and `token::StellarAssetAdminClient` –  Interface and client for convenience calling a SAC.
- `token::StellarAssetInterface` and `token::StellarAssetClient` – Convenience to use for Stellar assets?

@sisuresh Maybe we should take another approach: Remove `token::StellarAssetAdminInterface`. Add `token::StellarAssetInterface`. It'll keep the API smaller. The only reason to use the admin client is with Stellar Assets. Most of the time it would be more convenient to have the full Stellar Asset interface.

> I also tried just copying the methods into a combined interface

To get around this limitation we can move the Stellar Asset types into `token::stellar_asset::...`.

@sisuresh Wdyt?

**Comment by sisuresh** [comment] 2023-08-25 23:06
> The only reason to use the admin client is with Stellar Assets.

I don't think this is true due to the fact that `mint` is used on non-stellar assets, but your idea makes sense. I agree that if you're going to use an admin function, the full interface will probably be helpful.

**Comment by leighmcculloch** [comment] 2023-08-25 23:10
`mint` is part of the Stellar Asset interface though, and not part of the standard token interface. If it's part of the standard token interface, then we should probably revisit the split because splitting up the token interface was to separate Stellar Asset functions from standard token functions.

**Comment by leighmcculloch** [comment] 2023-08-29 17:44
I retract the suggestion of making a `token::StellarAssetInterface`, I think this risks contracts being developed that rely on it, when they could instead rely on `token::Interface`, which may reduce interoperability with the smaller standard interface.

**Comment by leighmcculloch** [comment] 2023-10-18 22:46
Closing because of the risks highlighted above and no further conversation. Anyone is welcome to comment on the issue for reopen if this should be pursued.

**Closed by leighmcculloch** 2023-10-18 22:46 UTC
