### ISSUE TITLE
User reporting LengthExceedsMax error when compiling contract

### ISSUE THREAD

**Issue by paulbellamy** [stellar/rs-soroban-sdk#450] opened 2022-08-17 15:28 UTC
When compiling https://github.com/Ryanmtate/soroban-examples/tree/feature/debenture-contract, the user reported an unexpected error about something being out of size.

On running it myself, I see:
```
168 | #[contractimpl(export_if = "export")]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: message: called `Result::unwrap()` on an `Err` value: LengthExceedsMax
```

Which, I think was the issue. Any more info here? Could we at least return a more helpful error message?

**Comment by leighmcculloch** [comment] 2022-08-17 16:48
Duplicate of https://github.com/stellar/rs-soroban-sdk/issues/384, which was fixed in https://github.com/stellar/rs-soroban-sdk/pull/402 and https://github.com/stellar/rs-soroban-sdk/pull/403.

**Closed by leighmcculloch** 2022-08-17 16:48 UTC
Labels: bug
