### ISSUE TITLE
Cannot use `env.prng` at the root of a test

### ISSUE THREAD

**Issue by kalepail** [stellar/rs-soroban-sdk#1243] opened 2024-03-15 19:14 UTC
### What version are you using?

`20.4.0`

### What did you do?

When trying to use `env.prng` inside a test I get an error
```rust
#[test]
fn test() {
    let env = Env::default();
    let rng = env.prng().gen::<u64>();

    println!("{:?}", rng);
}
```

### What did you expect to see?

A successful test run.

### What did you see instead?

```bash
    Finished test [unoptimized + debuginfo] target(s) in 0.28s
     Running unittests src/lib.rs (target/debug/deps/soroban_authplore-33bf1db7207db2bd)

running 1 test
thread 'test::test' panicked at /Users/tylervanderhoeven/.cargo/registry/src/index.crates.io-6f17d22bba15001f/soroban-env-host-20.2.2/src/host.rs:706:9:
HostError: Error(Context, InternalError)

Event log (newest first):
   0: [Diagnostic Event] topics:[error, Error(Context, InternalError)], data:"escalating error to panic"
   1: [Diagnostic Event] topics:[error, Error(Context, InternalError)], data:"no contract running"
```

I don't quite understand this error or why I can only use `env.prng` from within a contract.

fwiw I know I can run this inside an `env.as_contract(&contract_id, || { }` block but I just don't understand why this is required.

----

[Discord context](https://discord.com/channels/897514728459468821/1218220642936295454)

**Comment by leighmcculloch** [comment] 2024-03-15 21:55
There are some env functions that only work inside of an executing contract, because the env requires that a frame be on the stack. This is one of them. If we want the function callable outside of a frame, the env needs changing to support that. I don’t think there’s much the sdk can do without just fixing this in the env.

**Comment by jayz22** [comment] 2024-04-30 17:10
This is not a bug. The prng functions are supposed to be invoked with a contract, so that it has a frame with its own prng. 
It is part of the design that prng is contract-specific: every contract gets it own unique prng, and it cannot affect the `env` base prng or another contract's prng by any means. 
The base prng of the `env` is supposed to be non-observable by a contract. It is initialized once (from a public yet hard-to-predict entropy provided by the Stellar core) and can only be used to derive contract's prng. 
Here is the description of the original prng design https://github.com/stellar/rs-soroban-env/pull/802#issue-1698486375
Closing this issue. If you feel this is blocking testing or any feature development, please reopen and tag is as "enhancement".

**Closed by jayz22** 2024-04-30 17:10 UTC
