### ISSUE TITLE
Add SDK support for RNG

### ISSUE THREAD

**Issue by dmkozh** [stellar/rs-soroban-sdk#1065] opened 2023-08-23 16:02 UTC
Host-side support for RNG has been added back in preview 10, but we still don't have the corresponding SDK functions, thus this functionality effectively doesn't exist for most of the users.

**Comment by leighmcculloch** [comment] 2023-08-25 23:44
Duplicate of https://github.com/stellar/rs-soroban-sdk/issues/969 ?

**Closed** 2023-09-18 21:24 UTC
